
version: "3.9"

services:
  mini-bank:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    environment:
      - PGSQL_HOST=postgres
    ports:
      - "3000:3000"

networks:
  default:
    external: true
    name: contact_list_network
