version: "3.9"

services:
  postgres:
    image: postgres
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data/
#      - ./001-Create-Structure.sql:/docker-entrypoint-initdb.d/001-Create-Sctructure.sql

networks:
  default:
    external: true
    name: contact_list_network

volumes:
  database:
