version: "3.9"

services:
  postgres:
    image: postgres
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data/

networks:
  default:
    external: true
    name: contact_list_network

volumes:
  database:
