# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:14.17-buster
    environment: ci

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: master_user
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: contact_list
        options: >-
          --health-cmd pg_isready
          --health-interval 15s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Run code lint
      run: npm run lint

    - name: Run Typescript build
      run: npm run build

    - name: Prepare Typeorm config for CI
      run: mv ormconfig.env.ci ormconfig.env

    - name: Provide Typeorm a URL to connect and run migrations
      run: sed -i 's+PLACEHOLDER+postgresql://master_user:postgres@postgres:5432/contact_list+g' ormconfig.env

    - name: Run migrations
      run: npm run migration:run

    - name: Run E2E tests with coverage
      uses: paambaati/codeclimate-action@v2.7.5
      with:
        coverageCommand: npm run test:cov
      # Environment variables used while testing ( setting just the ones that does not have a default value )
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        DATABASE_URL: postgresql://master_user:postgres@postgres:5432/contact_list
        JWT_SECRET: superSecretDoNotTell

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.EMAIL}}
